// Wortschatz - Word Database
// Created by Aung Myo Thant (Lucius Tariq)
// 300 words from your personal word list
// User additions and deletions are stored in localStorage

const WORD_DATA = [

// === IDENTITY & REGISTRATION ===
{ type: 'noun', article: 'der', german: 'Name', english: 'name', strength: 0, wrongCount: 0 },
{ type: 'noun', article: 'der', german: 'Vorname', english: 'first name', strength: 0, wrongCount: 0 },
{ type: 'noun', article: 'der', german: 'Nachname', english: 'last name', strength: 0, wrongCount: 0 },
{ type: 'noun', article: 'der', german: 'Familienname', english: 'family name', strength: 0, wrongCount: 0 },
{ type: 'verb', article: null, german: 'geborene/r', english: 'born (as)', strength: 0, wrongCount: 0 },
{ type: 'noun', article: 'die', german: 'Nationalität', english: 'nationality', strength: 0, wrongCount: 0 },
{ type: 'noun', article: 'die', german: 'Staatsangehörigkeit', english: 'citizenship', strength: 0, wrongCount: 0 },
{ type: 'noun', article: 'die', german: 'Heimat', english: 'homeland', strength: 0, wrongCount: 0 },
{ type: 'noun', article: 'der', german: 'Ausweis', english: 'ID card', strength: 0, wrongCount: 0 },
{ type: 'noun', article: 'der', german: 'Pass', english: 'passport', strength: 0, wrongCount: 0 },
{ type: 'noun', article: 'das', german: 'Visum', english: 'visa', strength: 0, wrongCount: 0 },
{ type: 'verb', article: null, german: 'sich anmelden', english: 'to register', strength: 0, wrongCount: 0 },
{ type: 'verb', article: null, german: 'sich abmelden', english: 'to de-register', strength: 0, wrongCount: 0 },
{ type: 'noun', article: 'die', german: 'Anmeldung', english: 'registration', strength: 0, wrongCount: 0 },
{ type: 'noun', article: 'die', german: 'Abmeldung', english: 'de-registration', strength: 0, wrongCount: 0 },
{ type: 'noun', article: 'die', german: 'Personalien', english: 'personal data', strength: 0, wrongCount: 0 },
{ type: 'noun', article: 'der', german: 'Herr', english: 'Mr. / gentleman', strength: 0, wrongCount: 0 },
{ type: 'noun', article: 'die', german: 'Frau', english: 'Mrs. / woman', strength: 0, wrongCount: 0 },
{ type: 'noun', article: 'die', german: 'Adresse', english: 'address', strength: 0, wrongCount: 0 },
{ type: 'noun', article: 'der', german: 'Wohnort', english: 'place of residence', strength: 0, wrongCount: 0 },
{ type: 'verb', article: null, german: 'wohnen (in)', english: 'to live (in)', strength: 0, wrongCount: 0 },
{ type: 'verb', article: null, german: 'leben (in/seit)', english: 'to live (in/since)', strength: 0, wrongCount: 0 },
{ type: 'noun', article: 'die', german: 'Straße', english: 'street', strength: 0, wrongCount: 0 },
{ type: 'noun', article: 'der', german: 'Platz', english: 'square / place', strength: 0, wrongCount: 0 },
{ type: 'noun', article: 'der', german: 'Weg', english: 'way / path', strength: 0, wrongCount: 0 },
{ type: 'noun', article: 'die', german: 'Hausnummer', english: 'house number', strength: 0, wrongCount: 0 },
{ type: 'noun', article: 'die', german: 'Postleitzahl (PLZ)', english: 'postal code', strength: 0, wrongCount: 0 },

// === PERSONAL STATUS ===
{ type: 'noun', article: 'der', german: 'Familienstand', english: 'marital status', strength: 0, wrongCount: 0 },
{ type: 'verb', article: null, german: 'verheiratet', english: 'married', strength: 0, wrongCount: 0 },
{ type: 'verb', article: null, german: 'ledig', english: 'single', strength: 0, wrongCount: 0 },
{ type: 'verb', article: null, german: 'geschieden', english: 'divorced', strength: 0, wrongCount: 0 },
{ type: 'verb', article: null, german: 'verwitwet', english: 'widowed', strength: 0, wrongCount: 0 },
{ type: 'verb', article: null, german: 'verlobt', english: 'engaged', strength: 0, wrongCount: 0 },
{ type: 'verb', article: null, german: 'getrennt (leben)', english: 'to live separately', strength: 0, wrongCount: 0 },
{ type: 'verb', article: null, german: 'allein erziehend', english: 'single parent', strength: 0, wrongCount: 0 },
{ type: 'noun', article: 'das', german: 'Geschlecht', english: 'gender', strength: 0, wrongCount: 0 },
{ type: 'verb', article: null, german: 'männlich', english: 'male', strength: 0, wrongCount: 0 },
{ type: 'verb', article: null, german: 'weiblich', english: 'female', strength: 0, wrongCount: 0 },
{ type: 'verb', article: null, german: 'geboren sein (in/am)', english: 'to be born (in/on)', strength: 0, wrongCount: 0 },

// === DATES & AGE ===
{ type: 'noun', article: 'das', german: 'Datum', english: 'date', strength: 0, wrongCount: 0 },
{ type: 'noun', article: 'das', german: 'Geburtsdatum', english: 'date of birth', strength: 0, wrongCount: 0 },
{ type: 'noun', article: 'der', german: 'Geburtstag', english: 'birthday', strength: 0, wrongCount: 0 },
{ type: 'noun', article: 'das', german: 'Geburtsjahr', english: 'year of birth', strength: 0, wrongCount: 0 },
{ type: 'noun', article: 'der', german: 'Geburtsort', english: 'place of birth', strength: 0, wrongCount: 0 },
{ type: 'noun', article: 'das', german: 'Alter', english: 'age', strength: 0, wrongCount: 0 },
{ type: 'verb', article: null, german: 'jung', english: 'young', strength: 0, wrongCount: 0 },
{ type: 'verb', article: null, german: 'alt', english: 'old', strength: 0, wrongCount: 0 },

// === FAMILY ===
{ type: 'noun', article: 'die', german: 'Familie', english: 'family', strength: 0, wrongCount: 0 },
{ type: 'noun', article: 'die', german: 'Eltern', english: 'parents', strength: 0, wrongCount: 0 },
{ type: 'noun', article: 'der', german: 'Vater', english: 'father', strength: 0, wrongCount: 0 },
{ type: 'noun', article: 'die', german: 'Mutter', english: 'mother', strength: 0, wrongCount: 0 },
{ type: 'verb', article: null, german: 'der/die Erwachsene', english: 'adult', strength: 0, wrongCount: 0 },
{ type: 'noun', article: 'das', german: 'Kind', english: 'child', strength: 0, wrongCount: 0 },
{ type: 'noun', article: 'das', german: 'Baby', english: 'baby', strength: 0, wrongCount: 0 },
{ type: 'noun', article: 'der', german: 'Sohn', english: 'son', strength: 0, wrongCount: 0 },
{ type: 'noun', article: 'die', german: 'Tochter', english: 'daughter', strength: 0, wrongCount: 0 },
{ type: 'noun', article: 'der', german: 'Junge', english: 'boy', strength: 0, wrongCount: 0 },
{ type: 'noun', article: 'das', german: 'Mädchen', english: 'girl', strength: 0, wrongCount: 0 },
{ type: 'noun', article: 'der', german: 'Bruder', english: 'brother', strength: 0, wrongCount: 0 },
{ type: 'noun', article: 'die', german: 'Schwester', english: 'sister', strength: 0, wrongCount: 0 },
{ type: 'noun', article: 'die', german: 'Geschwister', english: 'siblings', strength: 0, wrongCount: 0 },
{ type: 'noun', article: 'die', german: 'Großeltern', english: 'grandparents', strength: 0, wrongCount: 0 },
{ type: 'noun', article: 'die', german: 'Großmutter', english: 'grandmother', strength: 0, wrongCount: 0 },
{ type: 'noun', article: 'der', german: 'Großvater', english: 'grandfather', strength: 0, wrongCount: 0 },
{ type: 'noun', article: 'der', german: 'Opa', english: 'grandpa', strength: 0, wrongCount: 0 },
{ type: 'noun', article: 'die', german: 'Oma', english: 'grandma', strength: 0, wrongCount: 0 },
{ type: 'noun', article: 'der', german: 'Onkel', english: 'uncle', strength: 0, wrongCount: 0 },
{ type: 'noun', article: 'die', german: 'Tante', english: 'aunt', strength: 0, wrongCount: 0 },

// === EXTENDED FAMILY ===
{ type: 'noun', article: 'die', german: 'Schwiegereltern', english: 'parents-in-law', strength: 0, wrongCount: 0 },
{ type: 'noun', article: 'der', german: 'Schwiegervater', english: 'father-in-law', strength: 0, wrongCount: 0 },
{ type: 'noun', article: 'die', german: 'Schwiegermutter', english: 'mother-in-law', strength: 0, wrongCount: 0 },
{ type: 'noun', article: 'der', german: 'Schwager', english: 'brother-in-law', strength: 0, wrongCount: 0 },
{ type: 'noun', article: 'die', german: 'Schwägerin', english: 'sister-in-law', strength: 0, wrongCount: 0 },
{ type: 'noun', article: 'der', german: 'Neffe', english: 'nephew', strength: 0, wrongCount: 0 },
{ type: 'noun', article: 'die', german: 'Nichte', english: 'niece', strength: 0, wrongCount: 0 },
{ type: 'noun', article: 'der', german: 'Cousin', english: 'male cousin', strength: 0, wrongCount: 0 },
{ type: 'noun', article: 'die', german: 'Cousine', english: 'female cousin', strength: 0, wrongCount: 0 },
{ type: 'verb', article: null, german: 'verwandt sein (mit)', english: 'to be related (to)', strength: 0, wrongCount: 0 },
{ type: 'noun', article: 'die', german: 'Verwandtschaft', english: 'kinship / relatives', strength: 0, wrongCount: 0 },
{ type: 'noun', article: 'die', german: 'Beziehung', english: 'relationship', strength: 0, wrongCount: 0 },
{ type: 'noun', article: 'die', german: 'Partnerschaft', english: 'partnership', strength: 0, wrongCount: 0 },
{ type: 'noun', article: 'das', german: 'Ehepaar', english: 'married couple', strength: 0, wrongCount: 0 },
{ type: 'noun', article: 'der', german: 'Ehemann', english: 'husband', strength: 0, wrongCount: 0 },

// === RELATIONSHIPS & MARRIAGE ===
{ type: 'noun', article: 'die', german: 'Ehefrau', english: 'wife', strength: 0, wrongCount: 0 },
{ type: 'noun', article: 'die', german: 'Liebe', english: 'love', strength: 0, wrongCount: 0 },
{ type: 'noun', article: 'der', german: 'Kuss', english: 'kiss', strength: 0, wrongCount: 0 },
{ type: 'verb', article: null, german: 'küssen', english: 'to kiss', strength: 0, wrongCount: 0 },
{ type: 'noun', article: 'die', german: 'Hochzeit', english: 'wedding', strength: 0, wrongCount: 0 },
{ type: 'noun', article: 'die', german: 'Heirat', english: 'marriage', strength: 0, wrongCount: 0 },
{ type: 'verb', article: null, german: 'heiraten', english: 'to marry', strength: 0, wrongCount: 0 },
{ type: 'verb', article: null, german: 'verheiratet sein (seit)', english: 'to be married (since)', strength: 0, wrongCount: 0 },
{ type: 'noun', article: 'die', german: 'Braut', english: 'bride', strength: 0, wrongCount: 0 },
{ type: 'noun', article: 'der', german: 'Bräutigam', english: 'groom', strength: 0, wrongCount: 0 },
{ type: 'noun', article: 'die', german: 'Scheidung', english: 'divorce', strength: 0, wrongCount: 0 },
{ type: 'noun', article: 'die', german: 'Trennung', english: 'separation', strength: 0, wrongCount: 0 },
{ type: 'verb', article: null, german: 'sich scheiden lassen', english: 'to get divorced', strength: 0, wrongCount: 0 },
{ type: 'noun', article: 'die', german: 'Erziehung', english: 'upbringing', strength: 0, wrongCount: 0 },
{ type: 'verb', article: null, german: 'erziehen', english: 'to raise / bring up', strength: 0, wrongCount: 0 },
{ type: 'noun', article: 'die', german: 'Geburt', english: 'birth', strength: 0, wrongCount: 0 },
{ type: 'noun', article: 'das', german: 'Aussehen', english: 'appearance', strength: 0, wrongCount: 0 },

// === APPEARANCE ===
{ type: 'verb', article: null, german: 'aussehen (wie)', english: 'to look (like)', strength: 0, wrongCount: 0 },
{ type: 'noun', article: 'die', german: 'Figur', english: 'figure', strength: 0, wrongCount: 0 },
{ type: 'verb', article: null, german: 'groß', english: 'tall / big', strength: 0, wrongCount: 0 },
{ type: 'verb', article: null, german: 'klein', english: 'small / short', strength: 0, wrongCount: 0 },
{ type: 'verb', article: null, german: 'dick', english: 'fat', strength: 0, wrongCount: 0 },
{ type: 'verb', article: null, german: 'dünn', english: 'thin', strength: 0, wrongCount: 0 },
{ type: 'verb', article: null, german: 'mager', english: 'meager / very thin', strength: 0, wrongCount: 0 },
{ type: 'verb', article: null, german: 'schlank', english: 'slim', strength: 0, wrongCount: 0 },
{ type: 'verb', article: null, german: 'schön', english: 'beautiful', strength: 0, wrongCount: 0 },
{ type: 'verb', article: null, german: 'hübsch', english: 'pretty', strength: 0, wrongCount: 0 },
{ type: 'verb', article: null, german: 'attraktiv', english: 'attractive', strength: 0, wrongCount: 0 },
{ type: 'verb', article: null, german: 'hässlich', english: 'ugly', strength: 0, wrongCount: 0 },
{ type: 'noun', article: 'das', german: 'Gesicht', english: 'face', strength: 0, wrongCount: 0 },
{ type: 'verb', article: null, german: 'blass', english: 'pale', strength: 0, wrongCount: 0 },

// === CHARACTER & PERSONALITY ===
{ type: 'verb', article: null, german: 'einen Bart tragen', english: 'to wear a beard', strength: 0, wrongCount: 0 },
{ type: 'verb', article: null, german: 'eine Brille tragen', english: 'to wear glasses', strength: 0, wrongCount: 0 },
{ type: 'noun', article: 'der', german: 'Charakter', english: 'character', strength: 0, wrongCount: 0 },
{ type: 'verb', article: null, german: 'nett', english: 'nice', strength: 0, wrongCount: 0 },
{ type: 'verb', article: null, german: 'freundlich', english: 'friendly', strength: 0, wrongCount: 0 },
{ type: 'verb', article: null, german: 'unfreundlich', english: 'unfriendly', strength: 0, wrongCount: 0 },
{ type: 'verb', article: null, german: 'frech', english: 'cheeky', strength: 0, wrongCount: 0 },
{ type: 'verb', article: null, german: 'sympathisch', english: 'likable', strength: 0, wrongCount: 0 },
{ type: 'verb', article: null, german: 'unsympathisch', english: 'unlikable', strength: 0, wrongCount: 0 },
{ type: 'verb', article: null, german: 'höflich', english: 'polite', strength: 0, wrongCount: 0 },
{ type: 'verb', article: null, german: 'unhöflich', english: 'impolite', strength: 0, wrongCount: 0 },
{ type: 'verb', article: null, german: 'treu', english: 'loyal', strength: 0, wrongCount: 0 },
{ type: 'verb', article: null, german: 'untreu', english: 'unfaithful', strength: 0, wrongCount: 0 },
{ type: 'verb', article: null, german: 'ehrlich', english: 'honest', strength: 0, wrongCount: 0 },
{ type: 'verb', article: null, german: 'unehrlich', english: 'dishonest', strength: 0, wrongCount: 0 },
{ type: 'verb', article: null, german: 'sportlich', english: 'athletic', strength: 0, wrongCount: 0 },
{ type: 'verb', article: null, german: 'unsportlich', english: 'unathletic', strength: 0, wrongCount: 0 },
{ type: 'verb', article: null, german: 'ruhig', english: 'calm', strength: 0, wrongCount: 0 },
{ type: 'verb', article: null, german: 'nervös', english: 'nervous', strength: 0, wrongCount: 0 },
{ type: 'verb', article: null, german: 'lebhaft', english: 'lively', strength: 0, wrongCount: 0 },
{ type: 'verb', article: null, german: 'neugierig', english: 'curious', strength: 0, wrongCount: 0 },
{ type: 'verb', article: null, german: 'komisch', english: 'funny / strange', strength: 0, wrongCount: 0 },
{ type: 'verb', article: null, german: 'Humor haben', english: 'to have a sense of humor', strength: 0, wrongCount: 0 },
{ type: 'verb', article: null, german: 'langweilig', english: 'boring', strength: 0, wrongCount: 0 },
{ type: 'verb', article: null, german: 'intelligent', english: 'intelligent', strength: 0, wrongCount: 0 },
{ type: 'verb', article: null, german: 'dumm', english: 'stupid', strength: 0, wrongCount: 0 },
{ type: 'verb', article: null, german: 'doof', english: 'silly', strength: 0, wrongCount: 0 },
{ type: 'verb', article: null, german: 'blöd', english: 'stupid / annoying', strength: 0, wrongCount: 0 },
{ type: 'verb', article: null, german: 'faul', english: 'lazy', strength: 0, wrongCount: 0 },
{ type: 'verb', article: null, german: 'fleißig', english: 'hardworking', strength: 0, wrongCount: 0 },
{ type: 'verb', article: null, german: 'ängstlich', english: 'anxious', strength: 0, wrongCount: 0 },
{ type: 'verb', article: null, german: 'feig', english: 'cowardly', strength: 0, wrongCount: 0 },
{ type: 'verb', article: null, german: 'mutig', english: 'brave', strength: 0, wrongCount: 0 },
{ type: 'verb', article: null, german: 'aktiv', english: 'active', strength: 0, wrongCount: 0 },
{ type: 'verb', article: null, german: 'passiv', english: 'passive', strength: 0, wrongCount: 0 },
{ type: 'verb', article: null, german: 'gut gelaunt', english: 'in a good mood', strength: 0, wrongCount: 0 },
{ type: 'verb', article: null, german: 'schlecht gelaunt', english: 'in a bad mood', strength: 0, wrongCount: 0 },
{ type: 'verb', article: null, german: 'lustig', english: 'funny', strength: 0, wrongCount: 0 },
{ type: 'verb', article: null, german: 'fröhlich', english: 'cheerful', strength: 0, wrongCount: 0 },
{ type: 'verb', article: null, german: 'zufrieden', english: 'satisfied', strength: 0, wrongCount: 0 },
{ type: 'verb', article: null, german: 'unzufrieden', english: 'unsatisfied', strength: 0, wrongCount: 0 },
{ type: 'verb', article: null, german: 'glücklich', english: 'happy', strength: 0, wrongCount: 0 },
{ type: 'verb', article: null, german: 'unglücklich', english: 'unhappy', strength: 0, wrongCount: 0 },
{ type: 'verb', article: null, german: 'romantisch', english: 'romantic', strength: 0, wrongCount: 0 },
{ type: 'verb', article: null, german: 'unromantisch', english: 'unromantic', strength: 0, wrongCount: 0 },
{ type: 'verb', article: null, german: 'ernst', english: 'serious', strength: 0, wrongCount: 0 },
{ type: 'verb', article: null, german: 'traurig', english: 'sad', strength: 0, wrongCount: 0 },
{ type: 'verb', article: null, german: 'eifersüchtig', english: 'jealous', strength: 0, wrongCount: 0 },
{ type: 'verb', article: null, german: 'bescheiden', english: 'modest', strength: 0, wrongCount: 0 },

// === HOUSING & RENTING ===
{ type: 'verb', article: null, german: 'stolz', english: 'proud', strength: 0, wrongCount: 0 },
{ type: 'verb', article: null, german: 'arrogant', english: 'arrogant', strength: 0, wrongCount: 0 },
{ type: 'verb', article: null, german: 'wohnen', english: 'to live', strength: 0, wrongCount: 0 },
{ type: 'noun', article: 'die', german: 'Wohnung', english: 'apartment', strength: 0, wrongCount: 0 },
{ type: 'noun', article: 'das', german: 'Haus', english: 'house', strength: 0, wrongCount: 0 },
{ type: 'noun', article: 'das', german: 'Gebäude', english: 'building', strength: 0, wrongCount: 0 },
{ type: 'noun', article: 'die', german: 'Wohngemeinschaft', english: 'shared apartment', strength: 0, wrongCount: 0 },
{ type: 'noun', article: 'das', german: 'Mietshaus', english: 'rental house', strength: 0, wrongCount: 0 },
{ type: 'noun', article: 'die', german: 'Eigentumswohnung', english: 'owned apartment', strength: 0, wrongCount: 0 },
{ type: 'noun', article: 'das', german: 'Hochhaus', english: 'high-rise building', strength: 0, wrongCount: 0 },
{ type: 'noun', article: 'das', german: 'Einfamilienhaus', english: 'single-family house', strength: 0, wrongCount: 0 },
{ type: 'verb', article: null, german: 'ausziehen', english: 'to move out', strength: 0, wrongCount: 0 },
{ type: 'verb', article: null, german: 'einziehen', english: 'to move in', strength: 0, wrongCount: 0 },
{ type: 'verb', article: null, german: 'umziehen', english: 'to move (change house)', strength: 0, wrongCount: 0 },
{ type: 'noun', article: 'der', german: 'Umzug', english: 'the move', strength: 0, wrongCount: 0 },
{ type: 'noun', article: 'das', german: 'Zimmer', english: 'room', strength: 0, wrongCount: 0 },
{ type: 'verb', article: null, german: 'bauen', english: 'to build', strength: 0, wrongCount: 0 },
{ type: 'verb', article: null, german: 'kaufen', english: 'to buy', strength: 0, wrongCount: 0 },
{ type: 'verb', article: null, german: 'verkaufen', english: 'to sell', strength: 0, wrongCount: 0 },
{ type: 'noun', article: 'die', german: 'Miete', english: 'rent', strength: 0, wrongCount: 0 },

// === ROOMS & BUILDING STRUCTURE ===
{ type: 'verb', article: null, german: 'mieten', english: 'to rent', strength: 0, wrongCount: 0 },
{ type: 'verb', article: null, german: 'vermieten', english: 'to rent out', strength: 0, wrongCount: 0 },
{ type: 'noun', article: 'die', german: 'Nebenkosten', english: 'utilities', strength: 0, wrongCount: 0 },
{ type: 'verb', article: null, german: 'inklusive', english: 'inclusive', strength: 0, wrongCount: 0 },
{ type: 'noun', article: 'der', german: 'Mietvertrag', english: 'rental contract', strength: 0, wrongCount: 0 },
{ type: 'noun', article: 'die', german: 'Kaution', english: 'deposit', strength: 0, wrongCount: 0 },
{ type: 'noun', article: 'der', german: 'Quadratmeter', english: 'square meter', strength: 0, wrongCount: 0 },
{ type: 'noun', article: 'die', german: 'Kündigung', english: 'notice / termination', strength: 0, wrongCount: 0 },
{ type: 'verb', article: null, german: 'kündigen', english: 'to give notice', strength: 0, wrongCount: 0 },
{ type: 'noun', article: 'die', german: 'Untermiete', english: 'sublease', strength: 0, wrongCount: 0 },
{ type: 'noun', article: 'der', german: 'Raum', english: 'room / space', strength: 0, wrongCount: 0 },
{ type: 'noun', article: 'das', german: 'Schlafzimmer', english: 'bedroom', strength: 0, wrongCount: 0 },
{ type: 'noun', article: 'das', german: 'Wohnzimmer', english: 'living room', strength: 0, wrongCount: 0 },
{ type: 'noun', article: 'das', german: 'Kinderzimmer', english: "children's room", strength: 0, wrongCount: 0 },
{ type: 'noun', article: 'das', german: 'Gästezimmer', english: 'guest room', strength: 0, wrongCount: 0 },
{ type: 'noun', article: 'die', german: 'Küche', english: 'kitchen', strength: 0, wrongCount: 0 },
{ type: 'noun', article: 'das', german: 'Bad / Badezimmer', english: 'bathroom', strength: 0, wrongCount: 0 },
{ type: 'noun', article: 'die', german: 'Toilette / das WC / das Klo', english: 'toilet', strength: 0, wrongCount: 0 },
{ type: 'noun', article: 'der', german: 'Gang / der Flur', english: 'hallway', strength: 0, wrongCount: 0 },
{ type: 'noun', article: 'die', german: 'Tür', english: 'door', strength: 0, wrongCount: 0 },
{ type: 'noun', article: 'das', german: 'Fenster', english: 'window', strength: 0, wrongCount: 0 },
{ type: 'noun', article: 'die', german: 'Wand', english: 'wall', strength: 0, wrongCount: 0 },
{ type: 'noun', article: 'die', german: 'Mauer', english: 'wall (brick)', strength: 0, wrongCount: 0 },
{ type: 'noun', article: 'der', german: 'Boden', english: 'floor / ground', strength: 0, wrongCount: 0 },
{ type: 'noun', article: 'die', german: 'Decke', english: 'ceiling / blanket', strength: 0, wrongCount: 0 },
{ type: 'noun', article: 'der', german: 'Eingang', english: 'entrance', strength: 0, wrongCount: 0 },
{ type: 'noun', article: 'der', german: 'Ausgang', english: 'exit', strength: 0, wrongCount: 0 },
{ type: 'noun', article: 'die', german: 'Treppe', english: 'stairs', strength: 0, wrongCount: 0 },
{ type: 'noun', article: 'die', german: 'Stufe', english: 'step', strength: 0, wrongCount: 0 },
{ type: 'noun', article: 'der', german: 'Lift / der Aufzug', english: 'elevator', strength: 0, wrongCount: 0 },
{ type: 'noun', article: 'das', german: 'Treppenhaus', english: 'staircase', strength: 0, wrongCount: 0 },

// === FURNITURE & HOME ITEMS ===
{ type: 'noun', article: 'der', german: 'Stock / das Stockwerk', english: 'floor / story', strength: 0, wrongCount: 0 },
{ type: 'noun', article: 'das', german: 'Erdgeschoss', english: 'ground floor', strength: 0, wrongCount: 0 },
{ type: 'noun', article: 'der', german: 'Keller', english: 'cellar / basement', strength: 0, wrongCount: 0 },
{ type: 'noun', article: 'das', german: 'Dach', english: 'roof', strength: 0, wrongCount: 0 },
{ type: 'noun', article: 'der', german: 'Kamin', english: 'chimney / fireplace', strength: 0, wrongCount: 0 },
{ type: 'noun', article: 'der', german: 'Ofen', english: 'stove / oven', strength: 0, wrongCount: 0 },
{ type: 'noun', article: 'der', german: 'Balkon', english: 'balcony', strength: 0, wrongCount: 0 },
{ type: 'noun', article: 'die', german: 'Terrasse', english: 'terrace', strength: 0, wrongCount: 0 },
{ type: 'noun', article: 'der', german: 'Hof', english: 'courtyard', strength: 0, wrongCount: 0 },
{ type: 'noun', article: 'der', german: 'Garten', english: 'garden', strength: 0, wrongCount: 0 },
{ type: 'noun', article: 'die', german: 'Garage', english: 'garage', strength: 0, wrongCount: 0 },
{ type: 'noun', article: 'die', german: 'Ausfahrt', english: 'driveway / exit', strength: 0, wrongCount: 0 },
{ type: 'noun', article: 'die', german: 'Aussicht', english: 'view', strength: 0, wrongCount: 0 },
{ type: 'noun', article: 'der', german: 'Komfort', english: 'comfort', strength: 0, wrongCount: 0 },
{ type: 'verb', article: null, german: 'einrichten', english: 'to furnish', strength: 0, wrongCount: 0 },
{ type: 'noun', article: 'die', german: 'Einrichtung', english: 'furnishing', strength: 0, wrongCount: 0 },
{ type: 'noun', article: 'die', german: 'Möbel', english: 'furniture', strength: 0, wrongCount: 0 },
{ type: 'verb', article: null, german: 'möbliert', english: 'furnished', strength: 0, wrongCount: 0 },
{ type: 'noun', article: 'der', german: 'Tisch', english: 'table', strength: 0, wrongCount: 0 },
{ type: 'noun', article: 'der', german: 'Schreibtisch', english: 'desk', strength: 0, wrongCount: 0 },
{ type: 'noun', article: 'die', german: 'Tischdecke', english: 'tablecloth', strength: 0, wrongCount: 0 },
{ type: 'noun', article: 'der', german: 'Stuhl', english: 'chair', strength: 0, wrongCount: 0 },
{ type: 'noun', article: 'der', german: 'Teppich', english: 'carpet', strength: 0, wrongCount: 0 },
{ type: 'noun', article: 'die', german: 'Gardine', english: 'curtain', strength: 0, wrongCount: 0 },
{ type: 'noun', article: 'der', german: 'Vorhang', english: 'curtain', strength: 0, wrongCount: 0 },
{ type: 'noun', article: 'der', german: 'Rolladen', english: 'shutters', strength: 0, wrongCount: 0 },
{ type: 'noun', article: 'der', german: 'Sessel', english: 'armchair', strength: 0, wrongCount: 0 },
{ type: 'noun', article: 'das', german: 'Sofa / die Couch', english: 'sofa', strength: 0, wrongCount: 0 },
{ type: 'noun', article: 'das', german: 'Regal', english: 'shelf', strength: 0, wrongCount: 0 },
{ type: 'noun', article: 'der', german: 'Schrank', english: 'closet / cupboard', strength: 0, wrongCount: 0 },
{ type: 'noun', article: 'das', german: 'Bett', english: 'bed', strength: 0, wrongCount: 0 },
{ type: 'noun', article: 'das', german: 'Kissen', english: 'pillow', strength: 0, wrongCount: 0 },
{ type: 'noun', article: 'der', german: 'Geschirrspüler', english: 'dishwasher', strength: 0, wrongCount: 0 },
{ type: 'noun', article: 'die', german: 'Waschmaschine', english: 'washing machine', strength: 0, wrongCount: 0 },

// === HOUSEHOLD TASKS ===
{ type: 'noun', article: 'der', german: 'Herd', english: 'stove', strength: 0, wrongCount: 0 },
{ type: 'noun', article: 'der', german: 'Kühlschrank', english: 'refrigerator', strength: 0, wrongCount: 0 },
{ type: 'noun', article: 'der', german: 'Backofen', english: 'oven', strength: 0, wrongCount: 0 },
{ type: 'noun', article: 'die', german: 'Mikrowelle', english: 'microwave', strength: 0, wrongCount: 0 },
{ type: 'noun', article: 'die', german: 'Kaffeemaschine', english: 'coffee machine', strength: 0, wrongCount: 0 },
{ type: 'noun', article: 'das', german: 'Geschirr', english: 'dishes', strength: 0, wrongCount: 0 },
{ type: 'noun', article: 'die', german: 'Dusche', english: 'shower', strength: 0, wrongCount: 0 },
{ type: 'noun', article: 'die', german: 'Badewanne', english: 'bathtub', strength: 0, wrongCount: 0 },
{ type: 'noun', article: 'das', german: 'Waschbecken', english: 'sink', strength: 0, wrongCount: 0 },
{ type: 'noun', article: 'das', german: 'Handtuch', english: 'towel', strength: 0, wrongCount: 0 },
{ type: 'noun', article: 'die', german: 'Garderobe', english: 'cloakroom', strength: 0, wrongCount: 0 },
{ type: 'noun', article: 'das', german: 'Bild', english: 'picture', strength: 0, wrongCount: 0 },
{ type: 'noun', article: 'der', german: 'Spiegel', english: 'mirror', strength: 0, wrongCount: 0 },
{ type: 'noun', article: 'die', german: 'Uhr', english: 'clock', strength: 0, wrongCount: 0 },
{ type: 'noun', article: 'die', german: 'Vase', english: 'vase', strength: 0, wrongCount: 0 },
{ type: 'noun', article: 'die', german: 'Heizung', english: 'heating', strength: 0, wrongCount: 0 },
{ type: 'verb', article: null, german: 'heizen', english: 'to heat', strength: 0, wrongCount: 0 },
{ type: 'noun', article: 'der', german: 'Strom', english: 'electricity', strength: 0, wrongCount: 0 },
{ type: 'noun', article: 'die', german: 'Steckdose', english: 'power outlet', strength: 0, wrongCount: 0 },
{ type: 'noun', article: 'das', german: 'Licht', english: 'light', strength: 0, wrongCount: 0 },
{ type: 'noun', article: 'die', german: 'Glühbirne', english: 'light bulb', strength: 0, wrongCount: 0 },
{ type: 'noun', article: 'die', german: 'Lampe', english: 'lamp', strength: 0, wrongCount: 0 },
{ type: 'noun', article: 'der', german: 'Schalter', english: 'switch', strength: 0, wrongCount: 0 },

// === WORLD, NATURE & LANDSCAPE ===
{ type: 'noun', article: 'der', german: 'Stecker', english: 'plug', strength: 0, wrongCount: 0 },
{ type: 'noun', article: 'der', german: 'Knopf', english: 'button', strength: 0, wrongCount: 0 },
{ type: 'verb', article: null, german: 'drücken', english: 'to press', strength: 0, wrongCount: 0 },
{ type: 'noun', article: 'der', german: 'Fernseher', english: 'television', strength: 0, wrongCount: 0 },
{ type: 'noun', article: 'das', german: 'Radio', english: 'radio', strength: 0, wrongCount: 0 },
{ type: 'noun', article: 'die', german: 'Anlage / die Stereoanlage', english: 'stereo system', strength: 0, wrongCount: 0 },
{ type: 'verb', article: null, german: 'an/ausmachen', english: 'to turn on/off', strength: 0, wrongCount: 0 },
{ type: 'verb', article: null, german: 'ein/ausschalten', english: 'to switch on/off', strength: 0, wrongCount: 0 },
{ type: 'noun', article: 'der', german: 'Haushalt', english: 'household', strength: 0, wrongCount: 0 },
{ type: 'verb', article: null, german: 'kochen', english: 'to cook', strength: 0, wrongCount: 0 },
{ type: 'verb', article: null, german: 'braten', english: 'to fry', strength: 0, wrongCount: 0 },
{ type: 'verb', article: null, german: 'backen', english: 'to bake', strength: 0, wrongCount: 0 },
{ type: 'verb', article: null, german: 'spülen', english: 'to wash (dishes)', strength: 0, wrongCount: 0 },
{ type: 'verb', article: null, german: 'abtrocknen', english: 'to dry (dishes)', strength: 0, wrongCount: 0 },
{ type: 'noun', article: 'das', german: 'Geschirrtuch', english: 'tea towel', strength: 0, wrongCount: 0 },
{ type: 'noun', article: 'das', german: 'Gerät', english: 'device', strength: 0, wrongCount: 0 },
{ type: 'verb', article: null, german: 'sauber machen', english: 'to clean', strength: 0, wrongCount: 0 },
{ type: 'verb', article: null, german: 'Ordnung machen', english: 'to tidy up', strength: 0, wrongCount: 0 },
{ type: 'verb', article: null, german: 'aufräumen', english: 'to tidy up', strength: 0, wrongCount: 0 },
{ type: 'verb', article: null, german: 'putzen', english: 'to clean', strength: 0, wrongCount: 0 },
{ type: 'noun', article: 'der', german: 'Eimer', english: 'bucket', strength: 0, wrongCount: 0 },
{ type: 'verb', article: null, german: 'staubsaugen', english: 'to vacuum', strength: 0, wrongCount: 0 },
{ type: 'noun', article: 'der', german: 'Staubsauger', english: 'vacuum cleaner', strength: 0, wrongCount: 0 },
{ type: 'noun', article: 'der', german: 'Besen', english: 'broom', strength: 0, wrongCount: 0 },
{ type: 'verb', article: null, german: 'wischen', english: 'to mop / wipe', strength: 0, wrongCount: 0 },
{ type: 'verb', article: null, german: 'waschen', english: 'to wash', strength: 0, wrongCount: 0 },
{ type: 'noun', article: 'die', german: 'Wäsche', english: 'laundry', strength: 0, wrongCount: 0 },
{ type: 'verb', article: null, german: 'bügeln', english: 'to iron', strength: 0, wrongCount: 0 },
{ type: 'noun', article: 'das', german: 'Bügeleisen', english: 'iron', strength: 0, wrongCount: 0 }
];
